OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
KEY_LOCK_ENABLE = no      # Enable KC_LOCK
DYNAMIC_MACRO_ENABLE = yes # Enable dynamic macros
RGBLIGHT_ENABLE = no
WPM_ENABLE = yes		   # Enable wpm
COMBO_ENABLE = no
BACKLIGHT_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
TAP_DANCE_ENABLE = yes	# Roughly 1k bytes, disable if full